name: docker cd

on:
  release:
    types: [published]

jobs:
  build-and-push-docker-image:
    name: Build & Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      -
        name: Build Jar
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: shadowJar
      -
        name: Push to Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: allanguigou/bot-is-gud/bot-is-gud
          tag_with_ref: true
