name: docker cd

on:
  release:
    types: [published]

jobs:
  build-and-push-docker-image:
    environment: production
    defaults:
      run:
        working-directory: bot
    name: Build & Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      -
        name: Build Jar
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: shadowJar
          build-root-directory: bot 
      -
        name: Prepare
        id: prepare
        run: |
          DOCKER_IMAGE=ghcr.io/allanguigou/bot-is-gud
          VERSION=${GITHUB_REF#refs/tags/}
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Push to Packages
        uses: docker/build-push-action@v2
        with:
          context: bot
          push: true
          platforms: linux/arm/v7
          tags: ${{ steps.prepare.outputs.tags }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.prepare.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
      -
        # TODO: definitely unnecessary to push image to packages & heroku
        name: Deploy to Heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_directory: bot/
          process_type: worker
