name: deploy

on:
  push:
    branches: [main]

concurrency: deploy

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        continue-on-error: true
        with:
          version: v1.53
          working-directory: go-is-gud
  build:
    defaults:
      run:
        working-directory: go-is-gud
    runs-on: ubuntu-latest
    needs: lint
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20.5'
      - name: Build
        run: go build .
      - name: Vet
        run: |
          go vet .
      - name: Login to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
            ghcr.io/${{ github.repository }}
      - name: Build and push Docker image
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
        with:
          context: go-is-gud
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: production
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'botisgud'
            slot-name: production
            publish-profile: ${{ secrets.AzureAppService_PublishProfile_12d7e4cdd1fc4f79807a0e1c52ee97ff }}
            images: 'ghcr.io/allanguigou/bot-is-gud:main'
