name: docker cd

on:
  release:
    types: [published]

jobs:
  build-and-push-docker-image:
    name: Build & Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Push to Packages
        uses: docker/build-push-actions@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: AllanGuigou/bot-is-gud/latest
          tag_with_ref: true
