name: lint & test ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    defaults:
      run:
        working-directory: go-is-gud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.8'
      - name: Install Dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      - name: Run Build
        run: go build .
      - name: Run vet & lint
        run: |
          go vet .
          golint .
      # - name: Run Tests
      #   run: cd test && go test -v